require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Load encryption keys from local file (auto-generated on first boot)
  # For production, use ENV variables to override these
  encryption_keys_file = Rails.root.join("config/local_encryption_keys.yml")
  
  # Auto-generate keys if file doesn't exist
  unless encryption_keys_file.exist?
    require 'securerandom'
    keys = {
      "primary_key" => SecureRandom.alphanumeric(32),
      "deterministic_key" => SecureRandom.alphanumeric(32),
      "key_derivation_salt" => SecureRandom.alphanumeric(32),
      "secret_key_base" => SecureRandom.hex(64)
    }
    File.write(encryption_keys_file, "# Auto-generated encryption keys for local development\n# This file is gitignored - do not commit to source control\n# For production, use environment variables instead\n\n#{keys.to_yaml}")
    puts "✅ Generated encryption keys at config/local_encryption_keys.yml"
  end
  
  local_keys = YAML.load_file(encryption_keys_file)
  
  # Secret key base - ENV takes precedence, then local file
  config.secret_key_base = ENV.fetch("SECRET_KEY_BASE") { local_keys["secret_key_base"] }

  # ActiveRecord Encryption - ENV takes precedence, then local file
  config.active_record.encryption.primary_key = ENV.fetch("ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY") { local_keys["primary_key"] }
  config.active_record.encryption.deterministic_key = ENV.fetch("ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY") { local_keys["deterministic_key"] }
  config.active_record.encryption.key_derivation_salt = ENV.fetch("ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT") { local_keys["key_derivation_salt"] }

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = false

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = false

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = false

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = false

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Codespaces environment configuration
  if ENV["CODESPACES"] == "true"
    # Relax CSRF origin check
    config.action_controller.forgery_protection_origin_check = false
    # Allow GitHub Codespaces hosts
    config.hosts << ".app.github.dev"
  end

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
